name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'metrics.svg'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_ZERO }}
          filename: metrics.svg
          user: Zero-Compiler
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          repositories_forks: yes
          
          # 语言统计
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%
          
          # 代码行数
          plugin_lines: yes
          plugin_lines_sections: base, repositories, history
          
          # 最近活动
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          # 贡献统计
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          # 常用插件
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          
          # 仓库流量统计
          plugin_traffic: yes
          
          # 热门仓库
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          
          # 代码变更统计
          plugin_code: yes
          plugin_code_languages: c++, rust, cmake, makefile
          plugin_code_load: 400
          plugin_code_days: 3
          plugin_code_visibility: all
